# Generated by Django 5.1.4 on 2025-01-10 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_room_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Понеділок'), ('Tuesday', 'Вівторок'), ('Wednesday', 'Середа'), ('Thursday', 'Четвер'), ('Friday', 'П’ятниця'), ('Saturday', 'Субота')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.day'),
        ),
    ]
